[package]
name = "power"
version = "1.0.0"
edition = "2021"

[dependencies]
json = "0.12"
serde = { version = "1.0", features = ["derive"] }
actix-web = "4.3"
env_logger = "0.10"
log = "0.4"
rand = "0.8"
serde_json = "1"
tokio = { version = "1.24.2", features = ["sync"] }
lambdaworks-crypto = { git = "https://github.com/lambdaclass/lambdaworks", rev = "366ac95" }
lambdaworks-math= { git = "https://github.com/lambdaclass/lambdaworks", rev = "366ac95" }
serde_cbor = "0.10"
